use std::borrow::Cow;

use indexmap::IndexMap;

use crate::expr::{ExprEntry, ExprForSource, ExprMatcher, ExprRule, MatchArm, parse_ref};
use crate::runtime_impl::env::{Scope, ScopeRef};
use crate::runtime_impl::node_id::NodeKind;
use crate::runtime_impl::ref_resolve::{
    ChainValue, RefKind, head_records, ref_head_parts, resolve_chain,
};
use crate::runtime_impl::value::{Record, Value};
use crate::walk::DirTree;
use crate::yaml::{RuleName, ValueExpr};

use super::with::build_with_scope;

/// Marks whether a candidate should push to `produced` in `assign_children`.
///
/// - `Direct`: the candidate is a direct dir/file write (or Splice/Match expansion that collect treats
///   transparently); `assign_children` is the producer and pushes its record into `produced`.
/// - `Expanded`: the candidate originates from For/Record/multi-node-Group expansion; the wrapping
///   producer is `collect_node_produced`, so `assign_children` must not push for it (otherwise the
///   body id would leak to the parent level and be double-counted).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProducedOwner {
    Direct,
    Expanded,
}

/// Four elements: macro-expanded entry, effective scope, origin rule name, and produced ownership marker.
///
/// Entries that require no expansion borrow from the original `entries`/`scope` (`Cow::Borrowed`) to avoid cloning.
/// Only entries generated by `for`/splice expansion with bindings are held as `Cow::Owned`.
///
/// `origin` indicates which rule body this entry originates from (for C2 refinement).
/// Direct writes (root body or inline direct writes) are `None`; splice-expansion origins are the innermost
/// splice target rule name `Some(N)`.
///
/// `ProducedOwner` distinguishes whether `assign_children` or `collect_node_produced` is responsible
/// for pushing the record into `produced`. For/Record/Group expansions are `Expanded`; all others are `Direct`.
pub type ScopedEntry<'a> = (
    Cow<'a, ExprEntry>,
    Cow<'a, Scope>,
    Option<RuleName>,
    ProducedOwner,
);

/// The kind of value bound in a `for` iteration.
///
/// - `Scalar`: a string value (inserted into scope as `Value::Scalar` as before)
/// - `Record`: a record value (inserted into scope as `Value::Record`, accessible via `${var.field}`)
pub(crate) enum ForBinding {
    Scalar(String),
    Record(Record),
}

/// Expands `for` and splice entries into a list of `ScopedEntry` (macro expansion).
///
/// - `ExprMatcher::For { var, source, rules }`: resolves `source` into a value list and recursively
///   expands `rules` with a new scope that binds each value to `var`. Each binding iteration is an
///   instance-scope boundary for ids; ids directly under `for_rules` (Splice/Group are transparent,
///   nested For and dir/file are opaque) are collected per binding from `tree` and overlaid as
///   `Value::RecordList` onto the binding scope (same shadow semantics as overlay: only the own binding
///   is visible; references outside the binding see the union via overlay).
/// - `ExprMatcher::Use { rule, with_args }`: recursively expands the rule's rules with a hermetic scope
///   (`build_with_scope`) that makes only the rule's declared with params visible, inserting the result at the
///   current position. When the splice entry's own count `is_relaxed()` (desugared optional), the
///   required-ness of expanded entries is relaxed (`count.relaxed(pattern.structural_max())`).
///   Splice cycles are checked at compile time, so recursion terminates.
/// - Other entries (Dir/File/Group) are passed through by borrowing the original `entry`/`scope`.
/// - For entry lists containing no `for`/splice, all entries are returned as borrows without any cloning.
///
/// `tree` is the current node's tree, used for per-binding id collection (for/splice expansion is the
/// content model of the same node, so the same `tree` is passed even in recursion).
#[allow(clippy::only_used_in_recursion)] // tree is part of the public API and passed through recursion
pub fn expand_entries<'a>(
    tree: &DirTree,
    entries: &'a [ExprEntry],
    scope: &'a Scope,
    rules: &'a IndexMap<RuleName, ExprRule>,
) -> Vec<ScopedEntry<'a>> {
    // Fast path: no `for`/splice/record/match/fetch/bind in this node — return all entries as borrows
    // without cloning.
    let needs_expand = entries.iter().any(|e| {
        matches!(
            e.matcher,
            ExprMatcher::For { .. }
                | ExprMatcher::Use { .. }
                | ExprMatcher::Group { .. }
                | ExprMatcher::Match { .. }
                | ExprMatcher::Fetch { .. }
                | ExprMatcher::Value { .. }
        )
    });
    if !needs_expand {
        // Direct write origin = None.
        return entries
            .iter()
            .map(|e| {
                (
                    Cow::Borrowed(e),
                    Cow::Borrowed(scope),
                    None,
                    ProducedOwner::Direct,
                )
            })
            .collect();
    }

    // `current_scope` folds in `value:` bindings as siblings are visited (sequential-let). It starts
    // as a borrow of the incoming scope and is promoted to an owned, extended scope on the first
    // value binding. All entries from that point on are evaluated against the extended scope.
    let mut current_scope: Cow<'a, Scope> = Cow::Borrowed(scope);

    let mut result: Vec<ScopedEntry<'a>> = Vec::new();
    for entry in entries {
        // A value binding mutates `current_scope`; all other arms only read it. Handle the binding
        // first so the read-only borrow used by the other arms does not overlap the mutation.
        if let ExprMatcher::Value { var, value } = &entry.matcher {
            // Sequential-let value binding: evaluate the scalar / list against the current scope
            // and bind it under the reserved `value.<var>` lex key, visible to later siblings.
            let bound = eval_value_expr(value, &current_scope);
            let mut extended = current_scope.into_owned();
            extended.bind_lex(NodeKind::Value, var.0.clone(), bound);
            current_scope = Cow::Owned(extended);
            // The binding itself emits no candidate entry (non-consuming).
            continue;
        }

        let scope: &Scope = &current_scope;
        match &entry.matcher {
            ExprMatcher::Value { .. } => unreachable!("Value handled above"),
            ExprMatcher::For {
                var,
                source,
                body: for_rules,
            } => {
                let bindings = resolve_for_source(source, scope);
                for binding in bindings {
                    let mut child_scope = scope.clone();
                    // The iteration variable is bound under `(NodeKind::Value, itervar)`, reachable
                    // from the body via `${value.<itervar>}`.
                    match binding {
                        ForBinding::Scalar(s) => {
                            child_scope.bind_lex(NodeKind::Value, var.0.clone(), Value::Scalar(s));
                        }
                        ForBinding::Record(r) => {
                            child_scope.bind_lex(NodeKind::Value, var.0.clone(), Value::Record(r));
                        }
                    };
                    // Recursive results may contain borrows into child_scope (local), so promote to Owned.
                    // origin follows the recursive result (direct writes in the for body are None; splice origins are Some).
                    let expanded = expand_entries(tree, for_rules, &child_scope, rules);
                    for (e, s, origin, _) in expanded {
                        result.push((
                            Cow::Owned(e.into_owned()),
                            Cow::Owned(s.into_owned()),
                            origin,
                            ProducedOwner::Expanded,
                        ));
                    }
                }
            }
            ExprMatcher::Use { rule, with_args } => {
                // Hermetic expansion: expand rule.rules in a scope that exposes only the rule's declared with params.
                if let Some(rule_def) = rules.get(rule) {
                    let s_scope = build_with_scope(rule_def, with_args, scope);
                    let expanded = expand_entries(tree, &rule_def.rules, &s_scope, rules);
                    for (e, s, inner_origin, owner) in expanded {
                        let owned = e.into_owned();
                        // Note: relaxation for optional splices (entry.count.is_relaxed()) is implemented
                        // via the new eval path (eval_use's push_relaxed + the relaxed() check in the
                        // post-loop check), so the count is not rewritten here (avoids dual implementation).
                        // origin: prefer innermost. Keep the origin from recursive results if present;
                        // fill only None (inline in this rule) entries with the current splice target name.
                        let origin = inner_origin.or_else(|| Some(rule.clone()));
                        result.push((Cow::Owned(owned), Cow::Owned(s.into_owned()), origin, owner));
                    }
                }
            }
            ExprMatcher::Group { subtree } => {
                // Group record-intro: non-consuming, transparent expansion in the same scope.
                // The subtree entries are expanded as if they were written inline at this position.
                let expanded = expand_entries(tree, subtree, scope, rules);
                for (e, s, origin, _) in expanded {
                    result.push((
                        Cow::Owned(e.into_owned()),
                        Cow::Owned(s.into_owned()),
                        origin,
                        ProducedOwner::Expanded,
                    ));
                }
            }
            ExprMatcher::Match { scrutinee, arms } => {
                // Sum elimination dispatch. `scrutinee` is the bare key (`${}` stripped at compile
                // time, e.g. `"c"`). Resolve it to a bound Record, read its `tag`, and transparently
                // expand the winning arm's subtree into the current node's content model (same shape
                // as Record-intro). Exhaustiveness is enforced at load time (E024/E025), so a tag
                // that matches no arm is defensively treated as no-expand.
                // scrutinee is the inner key inside `${...}` (e.g. `value.c`). Parse it with the
                // namespace grammar, resolve to (kind, id), and select the arm by the Record's tag.
                let sr = parse_ref(scrutinee);
                let (s_kind, s_id, _s_hops) = ref_head_parts(&sr.head, &sr.hops);
                if let Some(Value::Record(rec)) =
                    crate::runtime_impl::ref_resolve::head_value(scope, s_kind, &s_id)
                {
                    let tag = rec.tag.as_deref();
                    if let Some(MatchArm { subtree, .. }) =
                        arms.iter().find(|a| Some(a.tag.0.as_str()) == tag)
                    {
                        let expanded = expand_entries(tree, subtree, scope, rules);
                        for (e, s, origin, owner) in expanded {
                            result.push((
                                Cow::Owned(e.into_owned()),
                                Cow::Owned(s.into_owned()),
                                origin,
                                owner,
                            ));
                        }
                    }
                }
            }
            ExprMatcher::Fetch { .. } => {
                // Fetch is observation-only: it fills sets[id] during collect phase.
                // In the enforce phase it emits nothing into the candidate list (non-consuming).
            }
            _ => {
                // Dir/File/Group: pass through (inline origin = None). The scope is borrowed from the
                // incoming `'a` scope when no value binding has folded yet, or the owned extended
                // scope (cloned) once one has.
                result.push((
                    Cow::Borrowed(entry),
                    current_scope.clone(),
                    None,
                    ProducedOwner::Direct,
                ));
            }
        }
    }
    result
}

/// Evaluates a `value:` binding expression into a `Value` against the current scope.
///
/// - `ValueExpr::Scalar(s)` → `Value::Scalar` after interpolating `${...}` via `resolve_template`.
/// - `ValueExpr::List(items)` → `Value::Set` after interpolating each element. The set is used as a
///   `for ... in ${value.<var>}` source (each element binds a scalar).
pub(crate) fn eval_value_expr(value: &ValueExpr, scope: &Scope) -> Value {
    match value {
        ValueExpr::Scalar(s) => {
            Value::Scalar(crate::runtime_impl::template::resolve_template(s, scope))
        }
        ValueExpr::List(items) => {
            let resolved = items
                .iter()
                .map(|item| crate::runtime_impl::template::resolve_template(item, scope))
                .collect();
            Value::Set(resolved)
        }
    }
}

/// Resolves an `ExprForSource` into a list of `ForBinding`.
///
/// - `Literal(v)` → returns each element as `ForBinding::Scalar`.
/// - `Expr(s)` → delegates to `resolve_expr_source`.  Returns an empty Vec (= 0 iterations) for an
///   empty set or when the reference cannot be resolved.
pub(crate) fn resolve_for_source(source: &ExprForSource, scope: &Scope) -> Vec<ForBinding> {
    match source {
        ExprForSource::Literal(v) => v.iter().map(|s| ForBinding::Scalar(s.clone())).collect(),
        ExprForSource::Expr(s) => resolve_expr_source(s, scope),
    }
}

/// Parses the template string `s` and resolves it into a list of `ForBinding`.
///
/// Uses `parse_ref` with the new namespace grammar:
/// - `RefHead::Bare(name)` (rejected at compile) / `RefHead::WithNs { param }` /
///   `RefHead::RuleNs { rule_id }` / `RefHead::UseNs { id }`: the lookup key is
///   `name` / `param` / `rule_id` / `id` respectively. Effective hops come from `r.hops` (Bare) or
///   the tail (WithNs/RuleNs/UseNs/...).
/// - No effective hops → delegates to `resolve_bare_key(lookup_key, scope)`.
/// - Qualified hops (Regex/Dir/File) → `head_records` gathers all records from Γ_lex and Γ_set,
///   then `resolve_chain` is flat-mapped over each record.  This correctly handles splice id
///   sources held in Γ_set (RecordList/Set), which the previous implementation missed.
/// - `UseNs` is on the same path as `RuleNs`: the splice instance wrapper is referenced directly and
///   the desired record set is reached by explicit navigation (e.g. `for n in ${use.rec.dir.node}`).
/// - `Hop::Field` (unqualified) cannot appear here: compile-time `check_rule_var_scope` (E023)
///   rejects such references before configs reach the runtime.
fn resolve_expr_source(s: &str, scope: &Scope) -> Vec<ForBinding> {
    // If the string contains `${...}`, treat it as a variable reference.
    if let Some(start) = s.find("${") {
        let after = &s[start + 2..];
        if let Some(end) = after.find('}') {
            let key = &after[..end];
            let r = parse_ref(key);

            // Determine resolution kind, lookup id, and effective hops from the head namespace.
            // Value bindings (used as `for ... in ${value.names}`) live under `(NodeKind::Value, var)`.
            let (ref_kind, lookup_key_cow, effective_hops) = ref_head_parts(&r.head, &r.hops);
            let lookup_key: &str = &lookup_key_cow;

            if effective_hops.is_empty() {
                return resolve_bare_key(ref_kind, lookup_key, scope);
            }

            // One or more qualified hops (Regex/Dir/File): build a `NodePath` from the qualified path
            // and resolve it via `scope.resolve(&path)` (internally identical to the head_records +
            // resolve_chain flat-map of the conventional path).
            // Fall back to the conventional per-record loop only when a `NodePath` cannot be formed
            // (Bare head / legacy Field hop).
            if let Some(path) = crate::runtime_impl::ref_resolve::node_path_from_ref(
                ref_kind,
                lookup_key,
                effective_hops,
            ) {
                return match scope.resolve(&path) {
                    Some(ChainValue::Records(rs)) => {
                        rs.into_iter().map(ForBinding::Record).collect()
                    }
                    Some(ChainValue::Scalars(ss)) => {
                        ss.into_iter().map(ForBinding::Scalar).collect()
                    }
                    None => vec![],
                };
            }
            let recs = head_records(scope, ref_kind, lookup_key);
            let mut result: Vec<ForBinding> = Vec::new();
            for rec in &recs {
                match resolve_chain(rec, effective_hops) {
                    Some(ChainValue::Records(rs)) => {
                        result.extend(rs.into_iter().map(ForBinding::Record));
                    }
                    Some(ChainValue::Scalars(ss)) => {
                        result.extend(ss.into_iter().map(ForBinding::Scalar));
                    }
                    None => {}
                }
            }
            return result;
        }
    }
    // Bare string with no `${}`: return as a 1-element list.
    vec![ForBinding::Scalar(s.to_string())]
}

/// Resolves a `${var}`-form (bare key) and returns a list of `ForBinding`.
///
/// When var is present in scope:
/// - `Scalar` (Γ_lex) → `[ForBinding::Scalar(s)]`
/// - `Set` (Γ_lex) → each element as `ForBinding::Scalar`
/// - `Record` (Γ_lex) → `[ForBinding::Record(r.clone())]`
/// - `RecordList` (Γ_lex, from input passthrough) → each record as `ForBinding::Record`
/// - sets (Γ_set) → each record as `ForBinding::Record` (equivalent to bare `${id}` record iteration)
///
/// lex takes priority; falls back to env when not found in lex (follows resolution order).
/// Returns 0 iterations (empty Vec) when not found in scope.
///
/// - `RefKind::Bare` → transparent `Scope::get(id)` (lex → env).
/// - `RefKind::Qualified(kind)` → `lookup_lex(kind, id)` then `lookup_env(kind, id)`.
fn resolve_bare_key(ref_kind: RefKind, key: &str, scope: &Scope) -> Vec<ForBinding> {
    let from_value = |v: &Value| -> Vec<ForBinding> {
        match v {
            Value::Scalar(s) => vec![ForBinding::Scalar(s.clone())],
            Value::Set(items) => items
                .iter()
                .map(|s| ForBinding::Scalar(s.clone()))
                .collect(),
            Value::Record(r) => vec![ForBinding::Record(r.clone())],
            Value::RecordList(records) => records
                .iter()
                .map(|r| ForBinding::Record(r.clone()))
                .collect(),
        }
    };
    match ref_kind {
        RefKind::Bare => match scope.get(key) {
            Some(ScopeRef::Lex(v)) => from_value(v),
            Some(ScopeRef::Set(records)) => records
                .iter()
                .map(|r| ForBinding::Record(r.clone()))
                .collect(),
            None => vec![],
        },
        RefKind::Qualified(kind) => {
            if let Some(v) = scope.lookup_lex(kind, key) {
                from_value(v)
            } else if let Some(records) = scope.lookup_env(kind, key) {
                records
                    .iter()
                    .map(|r| ForBinding::Record(r.clone()))
                    .collect()
            } else {
                vec![]
            }
        }
    }
}
