version: 0

entry: root

rules:
  - rule: root
    ::
      - file: .type-dir.yaml
      - file: required.txt
      - file: extra.txt
        optional: true
      - file: opt.txt
        optional: true
