mod fixtures;

mod test_field_reference_in_declared_shape_is_compatible;
mod test_field_reference_not_in_declared_shape_is_incompatible;

mod both_arms_with_correct_captures_are_ok;
mod config_arm_with_service_capture_is_input_shape_mismatch;
mod service_arm_with_config_capture_is_input_shape_mismatch;
mod service_arm_with_service_capture_is_ok;

mod direct_ruletype_ref_to_existing_capture_is_ok;
mod direct_ruletype_ref_to_missing_capture_is_input_shape_mismatch;
mod direct_ruletype_ref_with_wrong_kind_is_node_kind_mismatch;

mod multi_hop_ref_to_existing_capture_is_ok;
mod multi_hop_ref_to_missing_capture_is_input_shape_mismatch;

mod for_binding_ruletype_missing_field_is_incompatible;
mod for_binding_ruletype_valid_field_is_compatible;

mod regex_qualified_reference_to_known_capture_is_ok;
mod regex_qualified_reference_to_unknown_capture_is_incompatible;

mod dir_qualified_reference_to_file_child_is_node_kind_mismatch;
mod file_qualified_reference_to_file_child_is_ok;

mod dotted_for_source_binding_to_existing_capture_is_ok;
mod dotted_for_source_binding_to_missing_capture_is_input_shape_mismatch;
